name = "pooopungames"
compatibility_date = "2024-03-24"

[build]
command = "npm run build"
cwd = "."
output_dir = "out"

[site]
bucket = ".next/static"
entry-point = "."

[env.production]
routes = [
  { pattern = "pooopungames.online", custom_domain = true }
]

[env]
NODE_VERSION = "18" 